const {test}=require('node:test');const assert=require('node:assert/strict');
const path=require('node:path');const {startFixture}=require('../../../acceptance/server.js');const {withNativeLinkDiagnostics}=require('./native-links.js');
// These existing component cases are exact equivalents for drawer history,
// focus/inert/scroll, catalog deletion, cancellation, gestures and breakpoints.
// The inventory identifies each original assertion and its specific child case.

test('main mobile navigation remaining cases',{skip:!process.env.PLAYWRIGHT_EXECUTABLE_PATH,timeout:60000},async t=>{
 const f=await startFixture({seed:false});
 try{
  const projects=[];for(const [name,identifier]of [['One','ONE'],['Two','TWO']]){const r=await f.api('/projects',{method:'POST',body:{name,identifier}});assert.ok(r.ok);projects.push(await r.json());}
  const group=await f.api('/project-groups',{method:'POST',body:{name:'Work'}});assert.ok(group.ok);const g=await group.json();assert.ok((await f.api('/project-groups',{method:'POST',body:{name:'Other'}})).ok);for(const project of projects)assert.ok((await f.api('/project-groups/assign',{method:'PUT',body:{project_id:project.id,group_id:g.id}})).ok);
  let page=await f.newPage();page.setDefaultTimeout(3000);page.setDefaultNavigationTimeout(15000);await page.setViewportSize({width:390,height:844});
  async function start(){await page.context().close();page=await f.newPage();page.setDefaultTimeout(3000);page.setDefaultNavigationTimeout(15000);await page.setViewportSize({width:390,height:844});assert.ok((await f.api('/projects/reorder',{method:'PUT',body:{ids:projects.map(project=>project.id)}})).ok);await page.goto(f.url('/ONE/issues'),{waitUntil:'domcontentloaded'});await page.locator('[data-mobile-open]').click();await page.waitForFunction(()=>history.state?.lificMobileNav?.depth===1);}
  await t.test('root/project focus trap, inert background, and trigger focus restoration',async()=>{
   await start();assert.equal(await page.locator('main').evaluate(el=>!!el.closest('[inert]')),true);assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Close navigation');
   await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('[data-mobile-root]').evaluate(el=>el.contains(document.activeElement)),true);assert.match(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')||document.activeElement.textContent),/Choose theme/);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Close navigation');
   await page.locator('[data-mobile-project-trigger="ONE"]').click();assert.equal(await page.locator('[data-mobile-root]').evaluate(el=>el.inert),true);assert.equal(await page.locator('[data-mobile-project]').evaluate(el=>el.inert),false);assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Projects');
   await page.keyboard.press('Escape');await page.waitForFunction(()=>history.state?.lificMobileNav?.depth===1);assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Open One navigation');
   await page.keyboard.press('Escape');await page.waitForFunction(()=>history.state?.lificMobileNav?.depth===0);assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Open navigation');
  });
  await t.test('native modified destination links preserve the open source drawer',async()=>{
   await start();await page.locator('[data-mobile-project-trigger="ONE"]').click();const link=page.locator('[data-mobile-project] a').filter({hasText:/^Issues$/});
   await withNativeLinkDiagnostics(page,async openPopup=>{for(const gesture of ['ctrl','middle'])await openPopup(link,gesture,async popup=>{await popup.waitForURL(f.url('/ONE/issues'));assert.equal(page.url(),f.url('/ONE/issues'));assert.equal(await page.locator('[data-mobile-navigation]').getAttribute('data-open'),'true');});});
  });
  await t.test('project context menu supports Inspect, disabled first Move up and Move down',async()=>{
   await start();await page.getByRole('button',{name:'Actions for One',exact:true}).click();assert.equal(await page.getByRole('menuitem',{name:'Move up',exact:true}).isDisabled(),true);await page.getByRole('menuitem',{name:'Inspect',exact:true}).waitFor();await page.waitForFunction(()=>!!document.activeElement?.closest('[role=menu]'));await page.getByRole('menuitem',{name:'Inspect',exact:true}).click();await page.getByRole('menu').waitFor({state:'hidden'});await page.getByRole('button',{name:'Actions for One',exact:true}).click();await page.getByRole('menuitem',{name:'Move down',exact:true}).click();
   const saved=await(await f.api('/projects')).json();assert.deepEqual(saved.map(project=>project.identifier),['TWO','ONE']);
  });
  await t.test('group rename preserves failed draft, Cancel/Escape focus, retries and Move down',async()=>{
   await start();await page.getByRole('button',{name:'Actions for Work',exact:true}).click();await page.getByRole('menuitem',{name:'Rename',exact:true}).click();const input=page.getByRole('textbox',{name:'Group name',exact:true});await input.fill('Personal');await input.press('Tab');assert.equal(await input.inputValue(),'Personal');
   await page.route('**/api/project-groups/*',route=>route.request().method()==='PATCH'?route.fulfill({status:409,json:{error:'Name already exists.'}}):route.continue());await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await input.inputValue(),'Personal');assert.match(await page.getByRole('alert').innerText(),/Name already exists/);await input.press('Escape');await input.waitFor({state:'hidden'});await page.waitForFunction(()=>history.state.lificMobileNav.depth===1);assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Actions for Work');
   await page.unroute('**/api/project-groups/*');await page.getByRole('button',{name:'Actions for Work',exact:true}).click();await page.getByRole('menuitem',{name:'Rename',exact:true}).click();await input.fill('Personal');await input.press('Enter');await input.waitFor({state:'hidden'});await page.getByRole('button',{name:'Actions for Personal',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Actions for Personal');await page.getByRole('button',{name:'Actions for Personal',exact:true}).click();await page.getByRole('menuitem',{name:'Move down',exact:true}).click();assert.deepEqual((await(await f.api('/project-groups')).json()).map(group=>group.name),['Other','Personal']);
  });
  await t.test('mobile theme chooser exposes current theme and menu semantics',async()=>{await start();const theme=page.getByRole('button',{name:'Choose theme, current: system',exact:true});assert.equal(await theme.getAttribute('aria-haspopup'),'menu');assert.equal(await theme.getAttribute('title'),'Choose theme, current: system');await theme.click();await page.getByRole('menuitem',{name:'System',exact:true}).waitFor();});
  await t.test('project order failure is announced in the open root pane',async()=>{await start();await page.route('**/api/projects/reorder',route=>route.fulfill({status:503,json:{error:'Connection lost.'}}));await page.getByRole('button',{name:'Actions for One',exact:true}).click();await page.getByRole('menuitem',{name:'Move down',exact:true}).click();assert.equal(await page.locator('[data-mobile-root] [role=alert]').innerText(),"Project order wasn't saved: Connection lost.");await page.unroute('**/api/projects/reorder');});
  await t.test('new project command unwinds drawer history without stale Forward reopen',async()=>{await start();await page.locator('[data-mobile-root]').getByRole('button',{name:'New project or group',exact:true}).click();await page.getByRole('menuitem',{name:'New project',exact:true}).click();await page.waitForURL(f.url('/projects/new'));await page.goBack();await page.waitForFunction(()=>document.querySelector('[data-mobile-navigation]').dataset.open==='false');assert.equal(await page.evaluate(()=>history.state?.lificMobileNav?.depth??0),0);});
  await t.test('LAN HTTP UUID fallback creates, restores and retains its namespace through Back and Forward',async()=>{
   const context=await f.browser.newContext({viewport:{width:390,height:844}});await context.addCookies([{name:'lific_token',value:f.token,url:f.origin}]);await context.addInitScript(token=>{localStorage.setItem('lific_token',token);Object.defineProperty(crypto,'randomUUID',{value:undefined,configurable:true});const original=crypto.getRandomValues.bind(crypto);window.randomValueCalls=0;crypto.getRandomValues=values=>{randomValueCalls++;return original(values);};},f.token);
   try{const p=await context.newPage();await p.goto(f.url('/ONE/issues'));assert.equal(await p.evaluate(()=>typeof crypto.randomUUID),'undefined');const before=await p.evaluate(()=>randomValueCalls);await p.locator('[data-mobile-open]').click();await p.waitForFunction(()=>history.state?.lificMobileNav?.depth===1);const session=await p.evaluate(()=>history.state.lificMobileNav.session);assert.match(session,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);assert.ok(await p.evaluate(()=>randomValueCalls)>before);
    await p.locator('[data-mobile-project-trigger="ONE"]').click();const state=await p.evaluate(()=>({state:history.state,length:history.length}));await p.reload();await p.waitForFunction(()=>document.querySelector('[data-mobile-navigation]').dataset.level==='project');assert.deepEqual(await p.evaluate(()=>({state:history.state,length:history.length})),state);assert.equal(await p.evaluate(()=>typeof crypto.randomUUID),'undefined');await p.goBack();await p.waitForFunction(()=>history.state?.lificMobileNav?.depth===1);assert.equal(await p.evaluate(()=>history.state.lificMobileNav.session),session);await p.goForward();await p.waitForFunction(()=>history.state?.lificMobileNav?.depth===2);assert.equal(await p.evaluate(()=>history.state.lificMobileNav.session),session);await p.locator('[data-mobile-project] [data-mobile-close]').click();await p.waitForFunction(()=>history.state.lificMobileNav.depth===0);assert.equal(await p.locator('[data-mobile-navigation]').getAttribute('data-open'),'false');
   }finally{await context.close();}
  });
 }finally{await f.close();}
});
