// main/web/tests/commentLinks.test.ts: observable routing and target outcomes through real mounted HTML.
const {test,before,after,expect,assert,product} = require('./harness');
const {startFixture}=require('../../../acceptance/server');
let f,comment;
before(async()=>{f=await startFixture();const response=await f.api(`/issues/${f.issue.id}/comments`,{method:'POST',body:{content:'linked comment'}});assert.equal(response.status,200);comment=await response.json();assert.equal((await f.api(`/projects/${f.project.id}`,{method:'PUT',body:{is_public:true}})).status,200);});
after(async()=>{await f?.close();});
async function target(route,authenticated=true){const page=await f.newPage({authenticated});page.setDefaultTimeout(3000);page.setDefaultNavigationTimeout(15000);await page.goto(f.url(route));return page;}
function routing(basePath,pathname){const location=new URL('http://localhost'+pathname);const window={history:{length:2},addEventListener(){}};return product('shell/assets/shell.js','portRouting',source=>source+';globalThis.portRouting=window.LificTopcoatRouting;', {window,location,document:{body:{dataset:{lificBasePath:basePath}},querySelector:()=>null}});}
test('keeps a public prefix inside the route rather than the base path',async()=>{for(const [base,path,expected]of [['','/public/LIF/issues/LIF-42','/public/LIF/issues/LIF-42'],['/app','/app/public/LIF/pages/7','/public/LIF/pages/7'],['','/LIF/issues/LIF-42','/LIF/issues/LIF-42']]){const live=routing(base,path);expect({basePath:live.basePath,route:live.path(path)}).toEqual({basePath:base,route:expected});}for(const route of [`/public/ACC/issues/${f.issue.identifier}`,`/public/ACC/pages/${f.page.id}`,`/ACC/issues/${f.issue.identifier}`]){const p=await target(route,!route.startsWith('/public'));try{const observed=await p.evaluate(()=>({basePath:LificTopcoatRouting.basePath,route:LificTopcoatRouting.currentPath()}));expect(observed).toEqual({basePath:'/app',route});}finally{await p.context().close();}}});
test('reads canonical anchors and normalized hash-route queries',async()=>{for(const suffix of [`#comment-${comment.id}`,`?view=all&comment=${comment.id}`,`#/ACC/issues/${f.issue.identifier}?view=all&comment=${comment.id}`]){const p=await target(`/ACC/issues/${f.issue.identifier}${suffix}`);try{await expect(p.locator(`#comment-${comment.id}`)).toHaveClass(/tc-comment--target/);}finally{await p.context().close();}}const p=await target(`/ACC/issues/${f.issue.identifier}#unrelated`);try{await expect(p.locator('.tc-comment--target')).toHaveCount(0);}finally{await p.context().close();}});
test('preserves route query parameters while carrying the comment target',async()=>{const p=await target(`/ACC/issues/${f.issue.identifier}?view=all`);try{await p.locator(`#comment-${comment.id} [aria-label="Link to this comment"]`).click();const url=new URL(p.url());expect(url.searchParams.get('view')).toBe('all');expect(url.hash).toBe(`#comment-${comment.id}`);}finally{await p.context().close();}});
test('keeps plain anchors on the current route and adopts routed hashes',async()=>{const p=await target(`/ACC/issues/${f.issue.identifier}`);try{await p.evaluate(id=>{location.hash=`comment-${id}`;},comment.id);expect(new URL(p.url()).pathname).toBe(`/app/ACC/issues/${f.issue.identifier}`);const other=await f.api('/issues',{method:'POST',body:{project_id:f.project.id,title:'Other comment route'}});assert.equal(other.status,200);const issue=await other.json();await p.evaluate(({identifier,id})=>{location.hash=`/ACC/issues/${identifier}?comment=${id}`;},{identifier:issue.identifier,id:comment.id});await expect(p).toHaveURL(new RegExp(`/app/ACC/issues/${issue.identifier}\\?comment=${comment.id}$`));}finally{await p.context().close();}});
test('separates a public URL base path from the resource route',async()=>{for(const [base,path,expected]of [['/lific','/lific/LIF/issues/LIF-42','/LIF/issues/LIF-42'],['','/LIF/pages/17','/LIF/pages/17']]){const live=routing(base,path);expect({basePath:live.basePath,route:live.path(path)}).toEqual({basePath:base,route:expected});}const p=await target(`/ACC/pages/${f.page.id}`);try{expect(await p.evaluate(()=>({basePath:LificTopcoatRouting.basePath,route:LificTopcoatRouting.path(location.pathname)}))).toEqual({basePath:'/app',route:`/ACC/pages/${f.page.id}`});await p.goto(f.url('/unrelated/path'));expect(await p.locator('[data-topcoat-collaboration],[data-topcoat-pages]').count()).toBe(0);}finally{await p.context().close();}});
