const {test,before,after,assert,expect}=require('./harness');
const {startFixture}=require('../../../acceptance/server');let f;
before(async()=>{f=await startFixture();});after(async()=>{await f?.close();});
async function create(route,body){const r=await f.api(route,{method:'POST',body});assert.equal(r.status,200);return r.json();}
async function live(){const issue=await create('/issues',{project_id:f.project.id,title:'Comment port'}),comment=await create(`/issues/${issue.id}/comments`,{content:'Original'}),page=await f.newPage();page.setDefaultTimeout(2000);page.setDefaultNavigationTimeout(15000);await page.goto(f.url(`/ACC/issues/${issue.identifier}`));await page.locator(`#comment-${comment.id}`).waitFor();return {page,issue,comment};}
// Real mounted native issue only: fixtures create rows through production APIs.
const {DatabaseSync}=require('node:sqlite');
function updateTimes(id,created,updated){const db=new DatabaseSync(f.database);try{db.prepare('UPDATE comments SET created_at=?,updated_at=? WHERE id=?').run(created,updated,id);}finally{db.close();}}
async function commentRows(issue){const response=await f.api(`/issues/${issue.id}/comments`);assert.equal(response.status,200);return response.json();}
test('renders mutation actions only for the comment author',async()=>{const {page,issue,comment}=await live();try{
 await expect(page.getByRole('button',{name:`Comment ${comment.id} actions`})).toHaveCount(1);await expect(page.getByRole('button',{name:`Comment ${comment.id} actions`})).toHaveCount(1);
 const reader=await create('/users',{username:`comment-reader-${issue.id}`,password:'acceptance-password-123',display_name:'Reader'});await create(`/projects/${f.project.id}/members`,{user_id:reader.id,role:'viewer'});
 const response=await f.api('/auth/login',{method:'POST',body:{identity:reader.username,password:'acceptance-password-123'}});assert.equal(response.status,200);const login=await response.json();assert.ok(login.token);
 await page.context().clearCookies();await page.context().addCookies([{name:'lific_token',value:login.token,url:f.origin,httpOnly:true}]);await page.reload();await page.locator(`#comment-${comment.id}`).waitFor();await expect(page.getByRole('button',{name:/^Comment \d+ actions$/})).toHaveCount(0);
 }finally{await page.context().close();}});
test('the thread revision changes for every way the rendered thread can change',async()=>{const {page,issue,comment}=await live();try{
 const thread=page.locator('section').filter({has:page.getByRole('heading',{name:'Comments',exact:true})}).last();const initial=await thread.innerHTML();await page.reload();expect(await thread.innerHTML()).toBe(initial);
 const newer=await create(`/issues/${issue.id}/comments`,{content:'Newer'});await page.reload();await expect(thread).toContainText('Newer');
 const older=await create(`/issues/${issue.id}/comments`,{content:'Older'});updateTimes(older.id,'2020-01-01 10:00:00','2020-01-01 10:00:00');await page.reload();const ids=await thread.locator('li[id^="comment-"]').evaluateAll(rows=>rows.map(row=>Number(row.id.slice(8))));expect(ids[0]).toBe(older.id);
 const updated=await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content:'Original, revised'}});assert.equal(updated.status,200);await page.reload();await expect(page.locator(`#comment-${comment.id}`)).toContainText('Original, revised');
 const removed=await f.api(`/comments/${newer.id}`,{method:'DELETE'});assert.equal(removed.status,200);await page.reload();await expect(page.locator(`#comment-${newer.id}`)).toHaveCount(0);
 const large=await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content:'x'.repeat(50000)}});assert.equal(large.status,200);await page.reload();await expect(page.locator(`#comment-${comment.id}`)).toContainText('x'.repeat(100));
 const bookkeeping=await page.locator('section').filter({has:page.getByRole('heading',{name:'Comments',exact:true})}).last().evaluate(node=>Object.entries(node).filter(([key,value])=>key.startsWith('_')&&typeof value==='string').map(([,value])=>value.length));assert.ok(bookkeeping.every(length=>length<80),'Revision bookkeeping must not retain a second full body');
 }finally{await page.context().close();}});
test('the thread revision tracks the mention roster the bodies render with',async()=>{const {page,issue,comment}=await live();try{
 const username=f.credentials.identity,content=`@${username} @ada`;
 const update=await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content}});assert.equal(update.status,200);
 const candidates=async()=>{const response=await f.api(`/projects/${f.project.id}/mention-candidates`);assert.equal(response.status,200);return response.json();};
 const roster=await candidates();const owner=roster.find(user=>user.username===username);assert.ok(owner,'The renderer receives a real project member roster');
 await page.reload();const chip=page.locator(`#comment-${comment.id} [data-mention]`).first();await expect(chip).toContainText(`@${owner.display_name}`);
 const initial=await page.locator(`#comment-${comment.id}`).innerHTML();await page.reload();expect(await page.locator(`#comment-${comment.id}`).innerHTML()).toBe(initial);
 const rename=await f.api('/auth/me',{method:'PATCH',body:{display_name:'Owner II'}});assert.equal(rename.status,200);assert.equal((await candidates()).find(user=>user.username===username).display_name,'Owner II');await page.reload();await expect(chip).toContainText('@Owner II');
 const added=await create('/users',{username:'ada',password:'acceptance-password-123',display_name:'Ada'});await create(`/projects/${f.project.id}/members`,{user_id:added.id,role:'viewer'});assert.ok((await candidates()).some(user=>user.username==='ada'));await page.reload();await expect(page.locator(`#comment-${comment.id} [data-mention]`)).toHaveCount(2);await expect(page.locator(`#comment-${comment.id} [data-mention]`).nth(1)).toContainText('@Ada');
 }finally{await page.context().close();}});

test('every comment body renders its diagrams inside the thread',async()=>{const {page,issue,comment}=await live();try{
 const updated=await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content:'```mermaid\ngraph TD\nLiveA-->LiveB\n```'}});assert.equal(updated.status,200);
 await create(`/issues/${issue.id}/comments`,{content:'```mermaid\ngraph TD\nLiveC-->LiveD\n```'});const third=await create(`/issues/${issue.id}/comments`,{content:'```mermaid\ngraph TD\nLiveE-->LiveF\n```'});await page.reload();await expect(page.locator('section').filter({has:page.getByRole('heading',{name:'Comments',exact:true})}).last().locator('svg')).toHaveCount(2);await expect(page.locator(`#comment-${third.id}`)).toContainText('too many diagrams');
 const revised=await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content:'```mermaid\ngraph TD\nRevised-->LiveB\n```'}});assert.equal(revised.status,200);assert.equal((await f.api(`/comments/${third.id}`,{method:'DELETE'})).status,200);await page.reload();await expect(page.locator('section').filter({has:page.getByRole('heading',{name:'Comments',exact:true})}).last().locator('svg')).toHaveCount(2);await expect(page.locator(`#comment-${comment.id} svg`)).toContainText('Revised');await expect(page.locator('section').filter({has:page.getByRole('heading',{name:'Comments',exact:true})}).last()).not.toContainText('too many diagrams');
 }finally{await page.context().close();}});
test('renders the original time and exact edited timestamp',async()=>{const {page,comment}=await live();try{updateTimes(comment.id,'2026-08-13 10:00:00','2026-08-13 10:05:00');await page.reload();const row=page.locator(`#comment-${comment.id}`);await expect(row).toContainText('edited');await expect(row.locator('[title="Edited 2026-08-13 10:05:00"]')).toHaveCount(1);expect(new Date(await row.locator('time').getAttribute('datetime')).toISOString()).toBe('2026-08-13T10:00:00.000Z');}finally{await page.context().close();}});
test('routes comment shortcuts by the focused interaction',async t=>{for(const action of ['submit','save','cancel','close-menu','new-escape'])await t.test(action,async()=>{const {page,issue,comment}=await live();try{if(action==='submit'||action==='new-escape'){const draft=page.getByPlaceholder('Write a comment…');await draft.fill('Keyboard posted');await draft.press(action==='submit'?'Control+Enter':'Escape');const response=await f.api(`/issues/${issue.id}/comments`),rows=await response.json();expect(rows.some(c=>c.content==='Keyboard posted')).toBe(action==='submit');}else if(action==='close-menu'){assert.equal((await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content:f.issue.identifier}})).status,200);await page.reload();const reference=page.locator(`#comment-${comment.id} [data-issue-ident]`);await reference.click({button:'right'});await expect(page.getByRole('menu',{name:'Issue reference actions'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('menu',{name:'Issue reference actions'})).toHaveCount(0);await expect(reference).toBeFocused();}else{await page.getByRole('button',{name:`Comment ${comment.id} actions`}).click();await page.getByRole('menuitem',{name:'Edit',exact:true}).click();const draft=page.locator(`#comment-${comment.id}`).getByRole('textbox');await draft.fill('Keyboard edited');await draft.press(action==='save'?'Control+Enter':'Escape');if(action==='save'){await expect.poll(async()=>{const r=await f.api(`/issues/${issue.id}/comments`);return (await r.json())[0].content;}).toBe('Keyboard edited');}else await expect(draft).toHaveCount(0);}}finally{await page.context().close();}});});
test('updates a comment through its typed API call',async()=>{const {page,issue,comment}=await live();try{await page.getByRole('button',{name:`Comment ${comment.id} actions`}).click();await page.getByRole('menuitem',{name:'Edit',exact:true}).click();await page.locator(`#comment-${comment.id}`).getByRole('textbox').fill('Revised');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator(`#comment-${comment.id}`)).toContainText('Revised');const response=await f.api(`/issues/${issue.id}/comments`);expect((await response.json())[0].content).toBe('Revised');}finally{await page.context().close();}});
test('deletes a comment through its typed API call',async()=>{const {page,issue,comment}=await live();try{page.on('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:`Comment ${comment.id} actions`}).click();await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete',exact:true}).click();await expect(page.locator(`#comment-${comment.id}`)).toHaveCount(0);const response=await f.api(`/issues/${issue.id}/comments`);expect(await response.json()).toEqual([]);}finally{await page.context().close();}});

test('sends the keyset cursor pair for older pages and never exceeds the cap',async()=>{const {page,issue}=await live();try{
 const db=new DatabaseSync(f.database);try{const owner=db.prepare('SELECT id FROM users WHERE is_admin=1 LIMIT 1').get();const insert=db.prepare('INSERT INTO comments(issue_id,user_id,content,created_at,updated_at) VALUES(?,?,?,?,?)');for(let index=0;index<101;index++){const at=`2026-08-13 10:${String(Math.floor(index/60)).padStart(2,'0')}:${String(index%60).padStart(2,'0')}`;insert.run(issue.id,owner.id,`Cursor row ${index}`,at,at);}}finally{db.close();}
 const response=await f.api(`/issues/${issue.id}/comments?order=desc&limit=51`);assert.equal(response.status,200);const newest=await response.json();assert.ok(newest.length<=51);const cursor=newest[49];assert.ok(cursor);const older=await f.api(`/issues/${issue.id}/comments?order=desc&limit=51&before_id=${cursor.id}&before_created_at=${encodeURIComponent(cursor.created_at)}`);assert.equal(older.status,200);const rows=await older.json();assert.ok(rows.length<=51);assert.ok(rows.every(row=>row.created_at<cursor.created_at||(row.created_at===cursor.created_at&&row.id<cursor.id)));
 await page.reload();await expect(page.locator('li[id^="comment-"]')).toHaveCount(50);await page.getByRole('button',{name:/older/i}).click();await expect(page.locator('li[id^="comment-"]')).toHaveCount(100);
 }finally{await page.context().close();}});
