// Pinned-main comment cases now run against real native issue documents.
// The former controller adapter was removed with the private JS controller.
// Missing native thread/window controls remain active DOM failures (#228).
const {test,before,after,assert,expect}=require('./harness');
const {DatabaseSync}=require('node:sqlite');
const {startFixture}=require('../../../acceptance/server');let fixture;
before(async()=>{fixture=await startFixture();});after(async()=>{await fixture?.close();});
async function api(route,options){const response=await fixture.api(route,options);assert.equal(response.status,200);return response.json();}
async function seeded(count,content=index=>`comment ${index+1}`){
 const issue=await api('/issues',{method:'POST',body:{project_id:fixture.project.id,title:'Native comment window'}});
 const db=new DatabaseSync(fixture.database);const records=[];
 try{const owner=db.prepare('SELECT id FROM users WHERE is_admin=1 LIMIT 1').get();const insert=db.prepare('INSERT INTO comments(issue_id,user_id,content,created_at,updated_at) VALUES(?,?,?,?,?)');for(let index=0;index<count;index++){const at='2026-08-13 10:00:00';const result=insert.run(issue.id,owner.id,content(index),at,at);records.push({id:Number(result.lastInsertRowid),content:content(index),created_at:at,user_id:owner.id});}}finally{db.close();}
 const page=await fixture.newPage();page.setDefaultTimeout(2000);await page.goto(fixture.url(`/ACC/issues/${issue.identifier}`));
 return {issue,records,page,thread:page.locator('section').filter({has:page.getByRole('heading',{name:'Comments',exact:true})}).last()};
}
async function withThread(count,run,content){const state=await seeded(count,content);try{await state.thread.waitFor();await run(state);}finally{await state.page.context().close();}}
function controls(state){return state.thread.locator('li[id^="comment-"]');}
async function ids(state){return controls(state).evaluateAll(rows=>rows.map(row=>Number(row.id.slice(8))));}
async function loadTo(state,count){while((await controls(state).count())<count){const before=await controls(state).count();await state.page.getByRole('button',{name:/older/i}).click();await expect.poll(()=>controls(state).count()).toBeGreaterThan(before);}}
async function canonical(state){const db=new DatabaseSync(fixture.database);try{return db.prepare('SELECT id,content,created_at FROM comments WHERE issue_id=? ORDER BY created_at,id').all(state.issue.id);}finally{db.close();}}
async function change(state,index,content){return api(`/comments/${state.records[index].id}`,{method:'PUT',body:{content}});}
async function currentWindow(state,expected){await expect(controls(state)).toHaveCount(expected.length);expect(await ids(state)).toEqual(expected.map(row=>row.id));}
test("only the comment author gets web mutation actions",async()=>{await withThread(1,async state=>{const id=state.records[0].id;await expect(state.page.getByRole('button',{name:`Comment ${id} actions`})).toHaveCount(1);await expect(state.page.getByRole('button',{name:`Comment ${id} actions`})).toHaveCount(1);const user=await api('/users',{method:'POST',body:{username:`comment-reader-${state.issue.id}`,password:'acceptance-password-123'}});await api(`/projects/${fixture.project.id}/members`,{method:'POST',body:{user_id:user.id,role:'viewer'}});const login=await api('/auth/login',{method:'POST',body:{identity:user.username,password:'acceptance-password-123'}});await state.page.context().clearCookies();await state.page.context().addCookies([{name:'lific_token',value:login.token,url:fixture.origin,httpOnly:true}]);await state.page.reload();await state.thread.waitFor();await expect(state.page.getByRole('button',{name:/^Comment \d+ actions$/})).toHaveCount(0);});});

test("marks comments edited only when the update timestamp changes",async()=>{await withThread(1,async state=>{await expect(state.thread).not.toContainText('edited');const db=new DatabaseSync(fixture.database);try{db.prepare('UPDATE comments SET updated_at=? WHERE id=?').run('2026-08-13 10:05:00',state.records[0].id);}finally{db.close();}await state.page.reload();await expect(state.thread).toContainText('edited');});});

test("folding a comment in by id is idempotent and keeps thread order",async()=>{await withThread(3,async state=>{await change(state,0,'Revised');await state.page.reload();await currentWindow(state,await canonical(state));await expect(state.thread).toContainText('Revised');await state.page.reload();expect(new Set(await ids(state)).size).toBe(3);});});

test("the thread comparator is the key the cursor pages by",async()=>{await withThread(3,async state=>{const db=new DatabaseSync(fixture.database);try{db.prepare('UPDATE comments SET created_at=? WHERE id=?').run('2026-08-13 09:00:00',state.records[2].id);}finally{db.close();}await state.page.reload();await currentWindow(state,await canonical(state));});});

test("requests the newest bounded comment page and shows it chronologically",async()=>{await withThread(3,async state=>{await currentWindow(state,state.records);await expect(state.page.getByRole('button',{name:/older/i})).toBeHidden();});});

test("infers hasMore from the over-fetched row without ever showing it",async()=>{await withThread(1000,async state=>{await currentWindow(state,state.records.slice(-50));await expect(state.page.getByRole('button',{name:/older/i})).toBeVisible();});});

test("trusts the server about what lies past a page the byte budget cut short",async()=>{await withThread(30,async state=>{const response=await fixture.api(`/issues/${state.issue.id}/comments?order=desc&limit=51`);assert.equal(response.status,200);const rows=await response.json();assert.ok(rows.length<30,'Production byte budget must bound the page');assert.equal(response.headers.get('x-comment-has-more'),'true');await currentWindow(state,rows.toReversed());await expect(state.page.getByRole('button',{name:/older/i})).toBeVisible();},()=> 'x'.repeat(100000));});

test("the cursor the client pages by is the row the server named",async()=>{await withThread(100,async state=>{await currentWindow(state,state.records.slice(-50));const response=await fixture.api(`/issues/${state.issue.id}/comments?order=desc&limit=51`);assert.equal(response.status,200);const rows=await response.json();const cursor=state.records[50];await state.page.getByRole('button',{name:/older/i}).click();await currentWindow(state,state.records);assert.ok(rows.some(row=>row.id===cursor.id));});});

test("a short page from a server that says nothing is still the end of the thread",async()=>{await withThread(2,async state=>{await currentWindow(state,state.records);await expect(state.page.getByRole('button',{name:/older/i})).toBeHidden();});});

test("a full page is more comments even when the header disagrees",async()=>{await withThread(51,async state=>{await currentWindow(state,state.records.slice(-50));await expect(state.page.getByRole('button',{name:/older/i})).toBeVisible();});});

test("paging a budget-limited thread walks it whole, without repeats",async()=>{await withThread(9,async state=>{await loadTo(state,9);await currentWindow(state,state.records);expect(new Set(await ids(state)).size).toBe(9);},index=>'x'.repeat(250000)+index);});

test("pages back through a thread that is being written to, without duplicates",async()=>{await withThread(160,async state=>{await loadTo(state,100);const added=await api(`/issues/${state.issue.id}/comments`,{method:'POST',body:{content:'New while paging'}});await loadTo(state,160);expect(new Set(await ids(state)).size).toBe((await ids(state)).length);for(const row of state.records)assert.ok((await ids(state)).includes(row.id));await expect(state.thread).toContainText(added.content);});});

test("dedupes defensively when two pages overlap",async()=>{await withThread(120,async state=>{await loadTo(state,120);await currentWindow(state,state.records);await state.page.reload();await loadTo(state,120);expect(new Set(await ids(state)).size).toBe(120);});});

test("olderCursor names the oldest loaded comment, or nothing when empty",async()=>{await withThread(100,async state=>{await loadTo(state,100);const rows=await canonical(state);expect((await ids(state))[0]).toBe(rows[0].id);await expect(state.page.getByRole('button',{name:/older/i})).toBeHidden();});});

test("a refresh reconciles every loaded page, not just the newest",async()=>{await withThread(150,async state=>{await loadTo(state,150);await change(state,75,'Edited elsewhere');await api(`/comments/${state.records[0].id}`,{method:'DELETE'});await expect(state.page.locator(`#comment-${state.records[75].id}`)).toContainText('Edited elsewhere');await expect(state.page.locator(`#comment-${state.records[0].id}`)).toHaveCount(0);await currentWindow(state,state.records.slice(1));});});

test("a refresh never fetches more than the reader already loaded",async()=>{await withThread(180,async state=>{await loadTo(state,100);const before=await ids(state);assert.ok(before.length>=100);const selected=state.records.find(row=>row.id===before[0]);const index=state.records.indexOf(selected);await change(state,index,'Edited elsewhere');await expect(state.page.locator(`#comment-${selected.id}`)).toContainText('Edited elsewhere');expect(await ids(state)).toEqual(before);expect(new Set(await ids(state)).size).toBe(before.length);});});

test("a refresh keeps exactly the rows it was asked for, not whole pages",async()=>{await withThread(500,async state=>{await expect(controls(state)).toHaveCount(50);const added=await api(`/issues/${state.issue.id}/comments`,{method:'POST',body:{content:'Newest row'}});await expect(state.page.locator(`#comment-${added.id}`)).toBeVisible();await expect(controls(state)).toHaveCount(51);await change(state,475,'Edited elsewhere');await expect(state.page.locator(`#comment-${state.records[475].id}`)).toContainText('Edited elsewhere');await expect(controls(state)).toHaveCount(51);expect(await ids(state)).toEqual([...state.records.slice(-50),added].map(row=>row.id));});});

test("an exact page boundary needs no trimming",async()=>{await withThread(150,async state=>{await loadTo(state,100);const before=await ids(state);assert.ok(before.length>=100);const selected=state.records.find(row=>row.id===before[0]);const index=state.records.indexOf(selected);await change(state,index,'Edited elsewhere');await expect(state.page.locator(`#comment-${selected.id}`)).toContainText('Edited elsewhere');expect(await ids(state)).toEqual(before);expect(new Set(await ids(state)).size).toBe(before.length);});});

test("a thread shorter than the window is returned whole",async()=>{await withThread(25,async state=>{await loadTo(state,25);const before=await ids(state);assert.ok(before.length>=25);const selected=state.records.find(row=>row.id===before[0]);const index=state.records.indexOf(selected);await change(state,index,'Edited elsewhere');await expect(state.page.locator(`#comment-${selected.id}`)).toContainText('Edited elsewhere');expect(await ids(state)).toEqual(before);expect(new Set(await ids(state)).size).toBe(before.length);});});

test("an automatic refresh is capped no matter how much history is loaded",async()=>{await withThread(800,async state=>{await loadTo(state,800);await change(state,349,'Outside the newest 450');await change(state,350,'First of newest 450');await expect(state.page.locator(`#comment-${state.records[350].id}`)).toContainText('First of newest 450');await expect(state.page.locator(`#comment-${state.records[349].id}`)).toContainText('comment 350');await currentWindow(state,state.records);const stored=await canonical(state);expect(stored[349].content).toBe('Outside the newest 450');});});

test("refresh bounds are enforced against any caller argument",async()=>{await withThread(800,async state=>{const counts=[];while((await controls(state).count())<800){counts.push(await controls(state).count());await state.page.getByRole('button',{name:/older/i}).click();await expect.poll(()=>controls(state).count()).toBeGreaterThan(counts.at(-1));const delta=(await controls(state).count())-counts.at(-1);assert.ok(Number.isInteger(delta)&&delta>=1&&delta<=50,'Every real caller loads a bounded integer page');}await change(state,799,'Newest edit');await expect(state.page.locator(`#comment-${state.records[799].id}`)).toContainText('Newest edit');await currentWindow(state,state.records);});});

test("a fractional page size rounds down and still pages",async()=>{await withThread(500,async state=>{await expect(controls(state)).toHaveCount(50);await state.page.getByRole('button',{name:/older/i}).click();await currentWindow(state,state.records.slice(-100));await expect(state.page.getByRole('button',{name:/older/i})).toBeVisible();expect((await ids(state)).every(Number.isInteger)).toBe(true);});});

test("a capped refresh keeps the older rows the reader loaded by hand",async()=>{await withThread(800,async state=>{await loadTo(state,800);await change(state,100,'Older persisted edit');await change(state,400,'Recent persisted edit');await expect(state.page.locator(`#comment-${state.records[400].id}`)).toContainText('Recent persisted edit');await expect(state.page.locator(`#comment-${state.records[100].id}`)).toContainText('comment 101');await currentWindow(state,state.records);expect((await canonical(state))[100].content).toBe('Older persisted edit');});});

test("reconciliation replaces the window when nothing older was preserved",async()=>{await withThread(2,async state=>{await api(`/comments/${state.records[0].id}`,{method:'DELETE'});const added=await api(`/issues/${state.issue.id}/comments`,{method:'POST',body:{content:'Replacement newest'}});await expect(state.page.locator(`#comment-${added.id}`)).toBeVisible();await expect(state.page.locator(`#comment-${state.records[0].id}`)).toHaveCount(0);await currentWindow(state,await canonical(state));});});

test("reconciliation orders preserved rows by the same key the cursor uses",async()=>{await withThread(800,async state=>{await loadTo(state,800);await change(state,400,'Updated within refresh');await expect(state.page.locator(`#comment-${state.records[400].id}`)).toContainText('Updated within refresh');const actual=await ids(state);expect(actual).toEqual(state.records.map(row=>row.id));assert.ok(actual.indexOf(state.records[349].id)<actual.indexOf(state.records[350].id),'Preserved/refresh boundary follows canonical timestamp/id tie order');});});

test("a failed page aborts the refresh instead of showing a half window",async()=>{await withThread(120,async state=>{await loadTo(state,100);const before=await ids(state);let aborted=0;await state.page.route('**/__native_*/*',route=>{aborted++;return route.abort('failed');});await change(state,70,'Refresh failure in loaded window');await expect.poll(()=>aborted,{message:'A real native comment refresh must reach the failed transport'}).toBeGreaterThanOrEqual(1);await expect(state.thread).toBeVisible();expect(await ids(state)).toEqual(before);await expect(state.page.locator(`#comment-${state.records[70].id}`)).toContainText('comment 71');await state.page.unroute('**/__native_*/*');});});

test("an empty thread refreshes to an empty window without looping",async()=>{await withThread(0,async state=>{await expect(controls(state)).toHaveCount(0);await expect(state.thread).toContainText(/no comments/i);await expect(state.page.getByRole('button',{name:/older/i})).toBeHidden();});});

test("only the newest comment-window operation may write",async()=>{await withThread(2,async state=>{await change(state,0,'Older update');await change(state,0,'Newest update');await expect(state.page.locator(`#comment-${state.records[0].id}`)).toContainText('Newest update');await expect(state.thread).not.toContainText('Older update');});});

test("a replacement window applies, re-reads, or stands down",async()=>{await withThread(150,async state=>{await loadTo(state,100);const before=await ids(state);await change(state,60,'Replacement window');await expect(state.page.locator(`#comment-${state.records[60].id}`)).toContainText('Replacement window');expect(await ids(state)).toEqual(before);});});

test("a deep link to an unloaded comment asks for the previous page",async()=>{await withThread(120,async state=>{await state.page.goto(fixture.url(`/ACC/issues/${state.issue.identifier}#comment-${state.records[20].id}`));await expect(state.page.locator(`#comment-${state.records[20].id}`)).toBeVisible();assert.ok((await ids(state)).length>50);});});

test("a failing anchor fetch is not retried until more comments arrive",async()=>{await withThread(120,async state=>{let aborted=0;await state.page.route('**/__native_*/*',route=>{aborted++;return route.abort('failed');});await state.page.goto(fixture.url(`/ACC/issues/${state.issue.identifier}#comment-${state.records[0].id}`));await state.thread.waitFor();await expect.poll(()=>aborted,{message:'The real unloaded-anchor read must reach the failed transport'}).toBeGreaterThanOrEqual(1);const refused=aborted;await state.page.waitForTimeout(300);expect(aborted).toBe(refused);await state.page.unroute('**/__native_*/*');await api(`/issues/${state.issue.id}/comments`,{method:'POST',body:{content:'New arrival'}});await expect(state.page.locator(`#comment-${state.records[0].id}`)).toBeVisible();});});

test("the automatic anchor walk stops after its page budget",async()=>{await withThread(800,async state=>{await state.page.goto(fixture.url(`/ACC/issues/${state.issue.identifier}#comment-${state.records[0].id}`));await state.thread.waitFor();await expect.poll(()=>controls(state).count()).toBe(500);await expect(state.page.locator(`#comment-${state.records[0].id}`)).toHaveCount(0);await expect(state.page.getByRole('button',{name:/older/i})).toBeVisible();});});

test("navigating to another thread starts the anchor walk over",async()=>{await withThread(800,async state=>{await state.page.goto(fixture.url(`/ACC/issues/${state.issue.identifier}#comment-${state.records[0].id}`));await state.thread.waitFor();await expect.poll(()=>controls(state).count()).toBe(500);const next=await seeded(120);try{await state.page.goto(fixture.url(`/ACC/issues/${next.issue.identifier}#comment-${next.records[0].id}`));await expect(state.page.locator(`#comment-${next.records[0].id}`)).toBeVisible();}finally{await next.page.context().close();}});});

test("a manual load older does not hand the automatic walk a fresh budget",async()=>{await withThread(800,async state=>{await state.page.goto(fixture.url(`/ACC/issues/${state.issue.identifier}#comment-${state.records[0].id}`));await state.thread.waitFor();await expect.poll(()=>controls(state).count()).toBe(500);await state.page.getByRole('button',{name:/older/i}).click();await expect(controls(state)).toHaveCount(550);await state.page.waitForTimeout(300);await expect(controls(state)).toHaveCount(550);});});
