const fs=require('node:fs'),path=require('node:path');
const {test,before,after,assert,expect,root}=require('./harness');
const {startFixture}=require('../../../acceptance/server');let f;
before(async()=>{f=await startFixture();});after(async()=>{await f?.close();});
async function create(route,body){const r=await f.api(route,{method:'POST',body});assert.equal(r.status,200);return r.json();}
async function live(){const issue=await create('/issues',{project_id:f.project.id,title:'Comment port'}),comment=await create(`/issues/${issue.id}/comments`,{content:'Original'}),page=await f.newPage();page.setDefaultTimeout(2000);page.setDefaultNavigationTimeout(15000);await page.goto(f.url(`/ACC/issues/${issue.identifier}`));await page.locator(`#comment-${comment.id}`).waitFor();return {page,issue,comment};}
async function component(){const page=await f.newPage();await page.goto(f.url('/__component_fixture'));await page.setContent('<section id="thread" data-comment-enabled="true"><span data-comment-count></span><div data-comment-thread></div><button data-comments-older>Older</button></section>');for(const file of ['vendor.marked.js','vendor.dompurify.js','vendor.mermaid.js','public.js'])await page.addScriptTag({path:path.join(root,'src/topcoat/public/assets',file)});await page.addScriptTag({path:path.join(root,'src/topcoat/issue_detail/editor/assets/editor.js')});let source=fs.readFileSync(path.join(root,'src/topcoat/issue_detail/collaboration/assets/collaboration.js'),'utf8').replace('={mount,commentMarkup,','={renderCommentList,renderCommentBodies,mount,commentMarkup,').replace(/  if \(typeof document[^\n]*mount\(root\);/,'');await page.addScriptTag({content:source});await page.evaluate(()=>{window.lificSession={state:{user:{id:3}}};const render=lificIssueEditor.renderMarkdown;window.renderCalls=[];lificIssueEditor.renderMarkdown=(node,text,options)=>{renderCalls.push(text);return render(node,text,options);};window.renderThread=(rows)=>{const root=document.querySelector('#thread');root._commentEdits||=new Map();root._comments=rows;LificTopcoatIssueCollaboration.renderCommentList(root,rows,true);return root.innerHTML;};});return page;}
const c=(over={})=>({id:42,user_id:3,author:'owner',author_display_name:'Owner',content:'Original',created_at:'2026-08-13 10:00:00',updated_at:'2026-08-13 10:00:00',...over});
test('renders mutation actions only for the comment author',async()=>{const p=await component();try{await p.evaluate(rows=>renderThread(rows),[c()]);await expect(p.locator('[data-comment-edit="42"]')).toHaveCount(1);await expect(p.locator('[data-comment-delete="42"]')).toHaveCount(1);await p.evaluate(rows=>{lificSession.state.user={id:9};renderThread(rows);},[c()]);await expect(p.locator('[data-comment-edit],[data-comment-delete]')).toHaveCount(0);}finally{await p.context().close();}});
test('the thread revision changes for every way the rendered thread can change',async()=>{const p=await component();try{const thread=[c({id:1,content:'one'}),c({id:2,content:'two',created_at:'2026-08-13 10:00:01'})];const initial=await p.evaluate(rows=>renderThread(rows),thread);const calls=await p.evaluate(()=>renderCalls.length);expect(await p.evaluate(rows=>renderThread(rows),structuredClone(thread))).toBe(initial);expect(await p.evaluate(()=>renderCalls.length)).toBe(calls);for(const rows of [[...thread,c({id:3})],[c({id:0,created_at:'2026-08-13 09:00:00'}),...thread],[{...thread[0],content:'one, revised'},thread[1]],[thread[0]]])expect(await p.evaluate(rows=>renderThread(rows),rows)).not.toBe(initial);expect(await p.evaluate(()=>renderCalls.filter(text=>text==='one, revised').length)).toBe(1);await p.evaluate(rows=>renderThread(rows),[c({content:'x'.repeat(50000)})]);const bookkeeping=await p.evaluate(()=>Object.entries(document.querySelector('#thread')).filter(([key,value])=>key.startsWith('_')&&key!=='_comments'&&key!=='_commentEdits'&&typeof value==='string').map(([,value])=>value.length));assert.ok(bookkeeping.every(length=>length<80),'Revision bookkeeping must not retain a second full body');}finally{await p.context().close();}});
test('the thread revision tracks the mention roster the bodies render with',async()=>{const {page,issue,comment}=await live();try{
 const username=f.credentials.identity,content=`@${username} @ada`;
 const update=await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content}});assert.equal(update.status,200);
 const candidates=async()=>{const response=await f.api(`/projects/${f.project.id}/mention-candidates`);assert.equal(response.status,200);return response.json();};
 const roster=await candidates();const owner=roster.find(user=>user.username===username);assert.ok(owner,'The renderer receives a real project member roster');
 await page.reload();const chip=page.locator(`#comment-${comment.id} .tc-comment__mention`).first();await expect(chip).toContainText(`@${owner.display_name}`);
 const initial=await page.locator(`#comment-${comment.id} [data-comment-content]`).innerHTML();await page.reload();expect(await page.locator(`#comment-${comment.id} [data-comment-content]`).innerHTML()).toBe(initial);
 const rename=await f.api('/auth/me',{method:'PATCH',body:{display_name:'Owner II'}});assert.equal(rename.status,200);assert.equal((await candidates()).find(user=>user.username===username).display_name,'Owner II');await page.reload();await expect(chip).toContainText('@Owner II');
 const added=await create('/users',{username:'ada',password:'acceptance-password-123',display_name:'Ada'});await create(`/projects/${f.project.id}/members`,{user_id:added.id,role:'viewer'});assert.ok((await candidates()).some(user=>user.username==='ada'));await page.reload();await expect(page.locator(`#comment-${comment.id} .tc-comment__mention`)).toHaveCount(2);await expect(page.locator(`#comment-${comment.id} .tc-comment__mention`).nth(1)).toContainText('@Ada');
 }finally{await page.context().close();}});

test('every comment body renders its diagrams inside the thread',async()=>{
 const p=await component();try{
  const rows=[c({id:1,content:'```mermaid\ngraph TD\nA-->B\n```'}),c({id:2,content:'```mermaid\ngraph TD\nC-->D\n```'})];
  await p.evaluate(rows=>renderThread(rows),rows);
  await expect(p.locator('[data-mermaid],.tc-public__diagram,svg')).toHaveCount(2);
  const rendered=await p.locator('[data-comment-thread]').innerHTML();
  await p.evaluate(rows=>renderThread(rows),structuredClone(rows));
  expect(await p.locator('[data-comment-thread]').innerHTML()).toBe(rendered);
  const three=[...rows,c({id:3,content:'```mermaid\ngraph TD\nE-->F\n```'})];
  await p.evaluate(rows=>renderThread(rows),three);
  await expect(p.locator('[data-comment-thread] svg')).toHaveCount(2);
  await expect(p.locator('#comment-3')).toContainText('too many diagrams');
  const revised=[{...rows[0],content:'```mermaid\ngraph TD\nRevised-->B\n```'},rows[1]];
  await p.evaluate(rows=>renderThread(rows),revised);
  await expect(p.locator('[data-comment-thread] svg')).toHaveCount(2);
  await expect(p.locator('#comment-1 svg')).toContainText('Revised');
  await expect(p.locator('[data-comment-thread]')).not.toContainText('too many diagrams');
 }finally{await p.context().close();}
 const {page,issue,comment}=await live();try{
  const first=await f.api(`/comments/${comment.id}`,{method:'PUT',body:{content:'```mermaid\ngraph TD\nLiveA-->LiveB\n```'}});assert.equal(first.status,200);
  await create(`/issues/${issue.id}/comments`,{content:'```mermaid\ngraph TD\nLiveC-->LiveD\n```'});
  const third=await create(`/issues/${issue.id}/comments`,{content:'```mermaid\ngraph TD\nLiveE-->LiveF\n```'});
  await page.reload();
  await expect(page.locator('[data-comment-thread] svg')).toHaveCount(2);
  await expect(page.locator(`#comment-${third.id}`)).toContainText('too many diagrams');
 }finally{await page.context().close();}
});
test('renders the original time and exact edited timestamp',async()=>{const p=await component();try{await p.evaluate(rows=>renderThread(rows),[c({updated_at:'2026-08-13 10:05:00'})]);await expect(p.locator('[data-comment-id="42"]')).toContainText('edited');await expect(p.locator('[title="Edited 2026-08-13 10:05:00"]')).toHaveCount(1);expect(await p.locator('time').getAttribute('datetime')).toBe('2026-08-13 10:00:00');}finally{await p.context().close();}});
test('routes comment shortcuts by the focused interaction',async t=>{for(const action of ['submit','save','cancel','close-menu','new-escape'])await t.test(action,async()=>{const {page,issue,comment}=await live();try{if(action==='submit'||action==='new-escape'){const draft=page.locator('[data-comment-draft]');await draft.fill('Keyboard posted');await draft.press(action==='submit'?'Control+Enter':'Escape');const response=await f.api(`/issues/${issue.id}/comments`),rows=await response.json();expect(rows.some(c=>c.content==='Keyboard posted')).toBe(action==='submit');}else if(action==='close-menu'){await page.addScriptTag({path:path.join(root,'src/topcoat/plans/assets/picker.js')});await page.evaluate(({id,identifier})=>{const body=document.querySelector(`#comment-${id} [data-comment-content]`);body.innerHTML=`<a data-issue-ident="${identifier}" href="/app/ACC/issues/${identifier}">${identifier}</a>`;LificTopcoatIssuePicker.bindReferences(body,{root:body,request:async route=>{const result=await lificSession.request(route);return result.data;}});},{id:comment.id,identifier:f.issue.identifier});const reference=page.locator(`#comment-${comment.id} [data-issue-ident]`);await reference.click({button:'right'});await expect(page.getByRole('menu',{name:'Issue reference actions'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('menu',{name:'Issue reference actions'})).toHaveCount(0);await expect(reference).toBeFocused();}else{await page.locator(`[data-comment-edit="${comment.id}"]`).click();const draft=page.locator(`[data-comment-edit-draft="${comment.id}"]`);await draft.fill('Keyboard edited');await draft.press(action==='save'?'Control+Enter':'Escape');if(action==='save'){await expect.poll(async()=>{const r=await f.api(`/issues/${issue.id}/comments`);return (await r.json())[0].content;}).toBe('Keyboard edited');}else await expect(draft).toHaveCount(0);}}finally{await page.context().close();}});});
test('updates a comment through its typed API call',async()=>{const {page,issue,comment}=await live();try{await page.locator(`[data-comment-edit="${comment.id}"]`).click();await page.locator(`[data-comment-edit-draft="${comment.id}"]`).fill('Revised');const request=page.waitForRequest(r=>r.method()==='PUT'&&r.url().endsWith(`/comments/${comment.id}`));await page.locator(`[data-comment-save="${comment.id}"]`).click();const sent=await request;expect(sent.postDataJSON()).toEqual({content:'Revised'});await expect(page.locator(`#comment-${comment.id}`)).toContainText('Revised');const response=await f.api(`/issues/${issue.id}/comments`);expect((await response.json())[0].content).toBe('Revised');}finally{await page.context().close();}});
test('deletes a comment through its typed API call',async()=>{const {page,issue,comment}=await live();try{page.on('dialog',dialog=>dialog.accept());const request=page.waitForRequest(r=>r.method()==='DELETE'&&r.url().endsWith(`/comments/${comment.id}`));await page.locator(`[data-comment-delete="${comment.id}"]`).click();await request;await expect(page.locator(`#comment-${comment.id}`)).toHaveCount(0);const response=await f.api(`/issues/${issue.id}/comments`);expect(await response.json()).toEqual([]);}finally{await page.context().close();}});

test('sends the keyset cursor pair for older pages and never exceeds the cap',async()=>{const {listComments}=require('./comments-adapter');const {product}=require('./harness');const pages=product('pages/assets/pages.js','LificTopcoatPages');const urls=[];const original=globalThis.fetch;try{globalThis.fetch=async url=>{urls.push(String(url));return new Response('[]');};await listComments(7,{created_at:'2026-08-13 10:00:00',id:951});await pages.PagesController.prototype.commentPage.call({session:{request:async route=>{urls.push('/api'+route);return {ok:true,data:[]};}}},9,{created_at:'2026-08-13 10:00:00',id:400});for(const [index,id]of [[0,951],[1,400]]){const url=new URL(urls[index],'http://localhost');expect(url.searchParams.get('before_created_at')).toBe('2026-08-13 10:00:00');expect(url.searchParams.get('before_id')).toBe(String(id));expect(url.searchParams.get('limit')).toBe('51');expect(url.searchParams.get('offset')).toBeNull();expect(url.searchParams.get('order')).toBe('desc');}}finally{globalThis.fetch=original;}});
