// main/e2e/context-menu.ts: current reference-menu focus/native browser actions, shell guards and preferences.
const fs=require('node:fs'),path=require('node:path');
const {test,before,after,assert,expect,root}=require('./harness');
const {startFixture}=require('../../../acceptance/server');let f;
before(async()=>{f=await startFixture();});after(async()=>{await f?.close();});
async function fixture(){const p=await f.newPage();p.setDefaultTimeout(2000);p.setDefaultNavigationTimeout(15000);await p.setViewportSize({width:390,height:844});p._portErrors=[];p.on('pageerror',error=>p._portErrors.push(error.message));await p.goto(f.url('/ACC/issues'));await p.addScriptTag({path:path.join(root,'src/topcoat/plans/assets/picker.js')});await p.evaluate(({href,identifier})=>{
 const container=document.createElement('section');container.id='menu-fixture';container.innerHTML=`<a id="trigger" data-issue-ident="${identifier}" href="${href}">Issue reference</a><a id="right-target" data-issue-ident="${identifier}">Right click target</a><input id="editor" aria-label="Editor">`;document.body.prepend(container);window.actions=[];
 window.menuFixture=LificTopcoatIssuePicker.bindReferences(container,{root:container,request:async route=>{const r=await lificSession.request(route);if(!r.ok)throw new Error(r.error);return r.data;},onPeek:()=>{actions.push('preview');document.querySelector('#editor').focus();}});
 },{href:f.url(`/ACC/issues/${f.issue.identifier}`),identifier:f.issue.identifier});return p;}
const menu=p=>p.getByRole('menu',{name:'Issue reference actions'});
async function open(p){await p.mouse.move(380,800);await p.locator('#trigger').click({button:'right'});await menu(p).waitFor();await expect(menu(p).getByRole('menuitem',{name:'Open preview',exact:true})).toBeFocused();}
async function closedAt(p,id){await expect(menu(p)).toHaveCount(0);await expect(p.locator(`#${id}`)).toBeFocused();}
async function use(body){const p=await fixture();try{await body(p);}finally{try{assert.deepEqual(p._portErrors||[],[]);}finally{await p.context().close();}}}
test('context menu: actionable items have 44px touch targets',()=>use(async p=>{await open(p);assert.ok((await menu(p).getByRole('menuitem').first().boundingBox()).height>=44);}));
test('context menu: arrows/Home/End wrap and one item owns the roving tab stop',()=>use(async p=>{
 await open(p);const items=menu(p).getByRole('menuitem');for(const [key,index]of [['ArrowDown',1],['End',1],['ArrowDown',0],['ArrowUp',1],['Home',0]]){await p.keyboard.press(key);await expect(items.nth(index)).toBeFocused();assert.equal(await items.nth(index).getAttribute('tabindex'),'0');assert.equal(await menu(p).locator('[tabindex="0"]').count(),1);}
}));
test('context menu: hover moves keyboard focus and Enter invokes one action',()=>use(async p=>{await open(p);await menu(p).getByRole('menuitem',{name:'Open in new tab'}).hover();await expect(menu(p).getByRole('menuitem',{name:'Open in new tab'})).toBeFocused();await menu(p).getByRole('menuitem',{name:'Open preview'}).hover();await p.keyboard.press('Enter');await closedAt(p,'editor');assert.deepEqual(await p.evaluate(()=>actions),['preview']);}));
for(const key of ['Tab','Shift+Tab','Escape'])test(`context menu: ${key} closes and restores trigger`,()=>use(async p=>{await open(p);await p.keyboard.press(key);await closedAt(p,'trigger');}));
test('context menu: consumed Escape misses later capture and bubble listeners',()=>use(async p=>{await p.evaluate(()=>{window.escapes=0;for(const capture of [true,false])window.addEventListener('keydown',event=>{if(event.key==='Escape')escapes++;},capture);});await open(p);await p.keyboard.press('Escape');await closedAt(p,'trigger');assert.equal(await p.evaluate(()=>escapes),0);}));
test('context menu: nonfocusable right-click trigger temporarily gains tabindex',()=>use(async p=>{await p.locator('#editor').focus();await p.locator('#right-target').click({button:'right'});await p.keyboard.press('Escape');await closedAt(p,'right-target');assert.equal(await p.locator('#right-target').getAttribute('tabindex'),'-1');await p.locator('#editor').focus();assert.equal(await p.locator('#right-target').getAttribute('tabindex'),null);}));
test('context menu: action focus and outside-click focus survive closing',()=>use(async p=>{await open(p);await menu(p).getByRole('menuitem',{name:'Open preview'}).click();await closedAt(p,'editor');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await expect(p.locator('#editor')).toBeFocused();await open(p);await p.locator('#editor').click();await closedAt(p,'editor');}));
test('context menu: replacing an open menu resets actual focus at identical coordinates',()=>use(async p=>{await open(p);for(let i=0;i<3;i++){await p.keyboard.press('End');await p.locator('#trigger').dispatchEvent('contextmenu',{bubbles:true,clientX:24,clientY:110});await expect(menu(p).getByRole('menuitem',{name:'Open preview'})).toBeFocused();}await p.keyboard.press('Escape');await closedAt(p,'trigger');}));
test('context menu: read-only references offer no disabled mutation action',()=>use(async p=>{await open(p);const actions=await menu(p).getByRole('menuitem').allTextContents();assert.deepEqual(actions,['Open preview','Open in new tab']);assert.equal(await menu(p).locator('[disabled]').count(),0);await p.keyboard.press('Escape');await p.evaluate(()=>{menuFixture.dispose();document.querySelector('#trigger').removeAttribute('data-issue-ident');});await p.locator('#trigger').click({button:'right'});await expect(menu(p)).toHaveCount(0);await p.keyboard.press('ArrowDown');await p.keyboard.press('Home');assert.deepEqual(await p.evaluate(()=>actions),[]);}));
for(const gesture of ['Control','middle'])test(`context menu: native ${gesture} reference opens real destination and bypasses action callback`,()=>use(async p=>{await open(p);await p.keyboard.press('Escape');const popupPromise=p.context().waitForEvent('page',{timeout:3000});await p.locator('#trigger').click(gesture==='middle'?{button:'middle'}:{modifiers:[gesture]});const popup=await popupPromise;try{await popup.waitForLoadState();await expect(popup).toHaveURL(f.url(`/ACC/issues/${f.issue.identifier}`));await expect(popup.locator('[data-topcoat-issue-detail]')).toBeVisible();assert.deepEqual(await p.evaluate(()=>actions),[]);}finally{await popup.close();}}));
test('context menu: plain and Space activation invoke the menu action once',()=>use(async p=>{await open(p);await menu(p).getByRole('menuitem',{name:'Open preview'}).click();await closedAt(p,'editor');assert.deepEqual(await p.evaluate(()=>actions),['preview']);assert.ok(!p.url().endsWith(`/issues/${f.issue.identifier}`));await open(p);await menu(p).getByRole('menuitem',{name:'Open preview'}).focus();await p.keyboard.press('Space');await closedAt(p,'editor');assert.deepEqual(await p.evaluate(()=>actions),['preview','preview']);}));
test('context menu: mobile navigation owns Control/Meta K/P shortcuts',()=>use(async p=>{await p.locator('[data-mobile-open]').click();for(const key of ['Control+k','Control+p','Meta+k','Meta+p'])await p.keyboard.press(key);await expect(p.locator('[data-topcoat-palette][open]')).toHaveCount(0);await p.keyboard.press('Escape');await p.keyboard.press('Control+k');await expect(p.getByRole('dialog',{name:'Jump or act'})).toBeVisible();}));
test('context menu: theme follows preference, OS changes and cross-tab storage/clear',async()=>{const p=await f.newPage();try{await p.goto(f.url('/__topcoat-preferences.js'));await p.setContent('<html><body>Preference component fixture</body></html>');await p.addStyleTag({url:f.url('/__topcoat-app.css')});await p.evaluate(async()=>{const prefs=await import('/app/__topcoat-preferences.js');prefs.initializePreferences();});
 const scheme=()=>p.evaluate(()=>getComputedStyle(document.documentElement).colorScheme);
 await p.evaluate(async()=>{const prefs=await import('/app/__topcoat-preferences.js');prefs.applyPreferences(prefs.savePreferences({theme:'dark'}));});
 await expect(p.locator('html')).toHaveAttribute('data-theme','dark');expect(await scheme()).toBe('dark');assert.equal(await p.evaluate(()=>localStorage.getItem('lific_theme')),'dark');
 await p.evaluate(async()=>{const prefs=await import('/app/__topcoat-preferences.js');prefs.applyPreferences(prefs.savePreferences({theme:'system'}));});
 await p.emulateMedia({colorScheme:'dark'});await expect.poll(scheme).toBe('dark');await p.emulateMedia({colorScheme:'light'});await expect.poll(scheme).toBe('light');
 const other=await p.context().newPage();try{await other.goto(f.url('/__topcoat-preferences.js'));await other.evaluate(()=>localStorage.setItem('lific_theme','dark'));await expect(p.locator('html')).toHaveAttribute('data-theme','dark');expect(await scheme()).toBe('dark');await other.evaluate(()=>localStorage.clear());await expect(p.locator('html')).toHaveAttribute('data-theme','system');expect(await scheme()).toBe('light');}finally{await other.close();}
}finally{await p.context().close();}});

test('context menu: Settings profile response updates session user and appearance control',async()=>{const p=await f.newPage();try{await p.goto(f.url('/settings'));await p.getByLabel('Display name',{exact:true}).fill('After');await p.getByRole('button',{name:'Save profile',exact:true}).click();await expect.poll(()=>p.evaluate(()=>lificSession.state.user?.display_name)).toBe('After');await p.getByLabel('Theme',{exact:true}).selectOption('dark');await expect(p.locator('html')).toHaveAttribute('data-theme','dark');await expect(p.getByLabel('Theme',{exact:true})).toHaveValue('dark');}finally{try{assert.deepEqual(p._portErrors||[],[]);}finally{await p.context().close();}}});

test('context menu: keyboard focus has a visible selected background',()=>use(async p=>{await open(p);const colors=await menu(p).getByRole('menuitem').evaluateAll(nodes=>nodes.map(node=>getComputedStyle(node).backgroundColor));assert.notEqual(colors[0],colors[1],'Focused menu action must have a distinct background');}));
test('context menu: native new-tab menu action reaches the real destination without preview callback',()=>use(async p=>{await open(p);const pending=p.context().waitForEvent('page');await menu(p).getByRole('menuitem',{name:'Open in new tab'}).click();const popup=await pending;try{await popup.waitForLoadState();await expect(popup).toHaveURL(f.url(`/ACC/issues/${f.issue.identifier}`));await expect(popup.locator('[data-topcoat-issue-detail]')).toBeVisible();assert.deepEqual(await p.evaluate(()=>actions),[]);await closedAt(p,'trigger');}finally{await popup.close();}}));
