// main/e2e/issue-topbar.ts assertions against the production issue toolbar.
const {test,before,after,assert,expect}=require('./harness');
const {startFixture}=require('../../../acceptance/server');let f;
before(async()=>{f=await startFixture();});after(async()=>{await f?.close();});
async function pageAt(width){const p=await f.newPage();p.setDefaultTimeout(1500);p.setDefaultNavigationTimeout(15000);await p.setViewportSize({width,height:900});p._portErrors=[];p.on('pageerror',error=>p._portErrors.push(error.message));await p.goto(f.url('/ACC/issues'));await p.locator('[data-issue-id]').first().waitFor();await p.evaluate(()=>document.fonts.ready);return p;}
for(const width of [360,640,700,767,1200]){
 test(`issue toolbar at ${width}px: layout, filter and create centers align within one pixel without overflow`,async()=>{const p=await pageAt(width);try{const boxes=await Promise.all([p.getByLabel('Layout',{exact:true}),p.getByLabel('Status',{exact:true}),p.getByRole('button',{name:'Create issue',exact:true})].map(n=>n.boundingBox()));assert.ok(boxes.every(Boolean));const ys=boxes.map(b=>b.y+b.height/2);assert.ok(Math.max(...ys)-Math.min(...ys)<=1,JSON.stringify({width,boxes}));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);}finally{try{assert.deepEqual(p._portErrors,[]);}finally{await p.context().close();}}});
 if(width<768)test(`issue toolbar at ${width}px: View options expands and focuses Display controls`,async()=>{const p=await pageAt(width);try{const toggle=p.getByRole('button',{name:'View options',exact:true});await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true');await p.locator('#issue-view-options').getByRole('button',{name:'Display',exact:true}).waitFor();assert.ok(await p.locator('#issue-view-options').evaluate(n=>n.contains(document.activeElement)));await toggle.click();}finally{try{assert.deepEqual(p._portErrors,[]);}finally{await p.context().close();}}});
 test(`issue toolbar at ${width}px: Quick create and New issue each invoke creation exactly once`,async()=>{const p=await pageAt(width);try{await p.getByRole('button',{name:'More create options',exact:true}).click();await p.getByRole('menuitem',{name:/^Quick create/}).click();await expect(p.locator('[data-topcoat-issue-create]')).toHaveCount(1);await p.goto(f.url('/ACC/issues'));await p.getByRole('button',{name:'New issue',exact:true}).click();await expect(p.locator('[data-topcoat-issue-create]')).toHaveCount(1);}finally{try{assert.deepEqual(p._portErrors,[]);}finally{await p.context().close();}}});
 test(`issue toolbar at ${width}px: search expands, fits viewport and collapses on Escape`,async()=>{const p=await pageAt(width);try{await p.getByRole('button',{name:'Search issues',exact:true}).click();const input=p.getByRole('searchbox',{name:'Search issues'});await input.fill('example');const b=await input.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=width);await input.press('Escape');await input.waitFor({state:'hidden'});}finally{try{assert.deepEqual(p._portErrors,[]);}finally{await p.context().close();}}});
}
