// main/web/tests/waits.test.ts: calendar/state contracts at real REST and native controls; text at live renderer.
const {test,before,after,expect,assert}=require('./harness');
const {startFixture}=require('../../../acceptance/server');let f;
before(async()=>{f=await startFixture();});after(async()=>{await f?.close();});
async function create(route,body){const r=await f.api(route,{method:'POST',body});assert.equal(r.status,200);return r.json();}
async function issue(){return create('/issues',{project_id:f.project.id,title:'Wait contract'});}
const offset=(day,n)=>{const date=new Date(`${day}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);};
async function render(waits,withoutBrowserClock=false){const item=await issue();for(const wait of waits){const body=wait.kind==='user'?{user:f.credentials.identity,note:wait.note}:{from:wait.earliest,until:wait.latest,note:wait.note};await create(`/issues/${item.id}/waits`,body);}const page=await f.newPage();try{if(withoutBrowserClock)await page.route('**/api/clock',route=>route.abort('failed'));await page.goto(f.url(`/ACC/issues/${item.identifier}`));const rows=page.locator('[data-wait-id]');await expect(rows).toHaveCount(waits.length);return await rows.allTextContents();}finally{await page.context().close();}}
const dateWait=(earliest,latest=earliest,note='',state='holding')=>({id:1,issue_id:1,kind:'date',earliest,latest,note,state});
const userWait={id:2,issue_id:1,kind:'user',user_id:7,username:'blake',display_name:'Blake',note:'real-device check',state:'holding'};
test('a date wait holds, comes due on its first day, and goes overdue after its last',async()=>{const clock=await (await f.api('/clock')).json();for(const [from,until,state]of [[1,2,'holding'],[0,1,'due'],[-1,0,'due'],[-2,-1,'overdue']]){const item=await issue(),wait=await create(`/issues/${item.id}/waits`,{from:offset(clock.today,from),until:offset(clock.today,until)});expect(wait.state).toBe(state);const r=await f.api(`/issues/${item.id}`);expect((await r.json()).waits[0].state).toBe(state);}});
test('a user wait holds until cleared',async()=>{const item=await issue(),wait=await create(`/issues/${item.id}/waits`,{user:f.credentials.identity,note:'real-device check'});expect(wait.state).toBe('holding');expect(wait.kind).toBe('user');const clear=await f.api(`/issues/${item.id}/waits/${wait.id}`,{method:'DELETE'});assert.equal(clear.status,200);expect(await (await f.api(`/issues/${item.id}/waits`)).json()).toEqual([]);});
test('date arithmetic stays on the calendar',async()=>{const item=await issue(),p=await f.newPage();try{await p.goto(f.url(`/ACC/issues/${item.identifier}`));const form=p.locator('[data-wait-create]');await form.locator('[name=kind]').selectOption('date');await form.locator('[name=from]').fill('2026-09-05');expect(await form.locator('[name=from]').inputValue()).toBe('2026-09-05');await form.locator('[name=from]').fill('2026-12-31');await form.locator('[name=until]').fill('2026-12-31');await form.locator('[name=until]').evaluate(input=>input.stepUp());expect(await form.locator('[name=until]').inputValue()).toBe('2027-01-01');await form.getByRole('button',{name:'Add wait'}).click();await expect.poll(async()=>{const response=await f.api(`/issues/${item.id}/waits`);assert.equal(response.status,200);const waits=await response.json();return waits.map(wait=>({earliest:wait.earliest,latest:wait.latest}));}).toContainEqual({earliest:'2026-12-31',latest:'2027-01-01'});}finally{await p.context().close();}});
test("today is the server's day at its UTC offset, not the browser's",async()=>{const clock=await (await f.api('/clock')).json();const item=await issue(),wait=await create(`/issues/${item.id}/waits`,{from:clock.today});expect(wait.state).toBe('due');for(const timezoneId of ['America/Chicago','UTC','Asia/Kolkata']){const context=await f.browser.newContext({timezoneId});try{await context.addCookies([{name:'lific_token',value:f.token,url:f.origin,httpOnly:true}]);const page=await context.newPage();await page.goto(f.url(`/ACC/issues/${item.identifier}`));await expect(page.locator(`[data-wait-id="${wait.id}"]`)).toContainText('due');}finally{await context.close();}}});
test("with no server clock yet, the server's own state stands",async()=>{const clock=await(await f.api('/clock')).json();expect((await render([dateWait(clock.today,clock.today,'','due')],true)).join(' ')).toContain('due');const yesterday=offset(clock.today,-1);expect((await render([dateWait(yesterday,yesterday,'','overdue')],true)).join(' ')).toContain('overdue');});
test('windows collapse a shared month',async()=>{const html=(await render([dateWait('2026-09-28','2026-09-29')])).join(' ');expect(html).toContain('28 to 29');expect((await render([dateWait('2026-09-28','2026-10-02')])).join(' ')).toContain(' to ');});
test('the detail headline names the state',async()=>{const clock=await(await f.api('/clock')).json();expect((await render([userWait])).join(' ')).toContain(`Waiting on Acceptance Admin (@${f.credentials.identity})`);const future=offset(clock.today,1);expect((await render([dateWait(future)])).join(' ')).toContain('Waiting until ');expect((await render([dateWait(clock.today,clock.today,'','due')])).join(' ')).toContain('Due to check since ');expect((await render([dateWait(offset(clock.today,-2),offset(clock.today,-1),'','overdue')])).join(' ')).toMatch(/Overdue since .*expected /);});
test('the chip shows the most pressing wait and counts the rest',async t=>{
 await t.test('an issue with no waits has no summary chip',async()=>{const item=await issue(),p=await f.newPage();try{await p.goto(f.url('/ACC/issues'));const row=p.locator(`[data-issue-id="${item.id}"]`);await row.waitFor();await expect(row.locator('.tc-issues__wait')).toHaveCount(0);}finally{await p.context().close();}});
 await t.test('a user-only summary is the username',async()=>{const item=await issue();await create(`/issues/${item.id}/waits`,{user:f.credentials.identity,note:'real-device check'});const p=await f.newPage();try{await p.goto(f.url('/ACC/issues'));const row=p.locator(`[data-issue-id="${item.id}"]`);await row.waitFor();const chips=row.locator('.tc-issues__wait');await expect(chips).toHaveCount(1);await expect(chips).toHaveText(`@${f.credentials.identity}`);}finally{await p.context().close();}});
 await t.test('the most pressing date carries the other user wait',async()=>{const item=await issue();await create(`/issues/${item.id}/waits`,{user:f.credentials.identity,note:'real-device check'});await create(`/issues/${item.id}/waits`,{from:'2026-09-28',until:'2026-09-29',note:'filing office'});const p=await f.newPage();try{await p.goto(f.url('/ACC/issues'));const row=p.locator(`[data-issue-id="${item.id}"]`);await row.waitFor();const chips=row.locator('.tc-issues__wait');expect(await chips.count()).toBe(1);await expect(chips).toContainText(/^overdue /);const title=await chips.getAttribute('aria-label');expect(title).toContain('(filing office)');expect(title).toContain(`Waiting on Acceptance Admin (@${f.credentials.identity})`);await expect(chips).toContainText('+1');}finally{await p.context().close();}});
});
